### ISSUE TITLE
Optionally prevent popup and redirect on main site?

### ISSUE THREAD

**Issue by rugk** [rugk/mastodon-simplified-federation#15]
Is there someone, who would like to have a way to prevent (aka "quickly close") these popups of Mastodon and redirect the follow/interaction request in the main window/tab directly?

Is this something you may find useful?

If so, feel free to upvote or – if you'd like – send a PR. It may require some thoughts, but should be "quite" easy to implement. 

Obviously it should be an optional (opt-in) feature.

**Comment by rugk** [comment]
Note this behaviour already (more or less accidentally) happens, if you leave the popup window open, and click on the follow/interaction button again.

**Comment by naught101** [comment]
Yes please!

I would MUCH prefer to be directed to the user's page on my home instance (e.g. https://my.instance/@user@other.instance). That way I can see if they are posting stuff that I'm interested in, and check out their network on my instance.

**Comment by rugk** [comment]
Hmm I'm kinda confused about this issue and I likely did not notice I created a duplicate by myself.

If I am not mistaken, this is already implemented in v1.3 and you can check the checkbox in the settings to use it. See https://github.com/rugk/mastodon-simplified-federation/releases/tag/v1.3

Also this seems to be a dupe of https://github.com/rugk/mastodon-simplified-federation/issues/44
