### ISSUE TITLE
Single Window Interactions

### ISSUE THREAD

**Issue by Malsasa** [rugk/mastodon-simplified-federation#44]
## Background
It's tiresome to open a new window each time interacting (I mean here all activities: following, commenting, retooting, liking) with user at different instance. At the moment, Simplified Federation indeed helps a lot skipping username input step, thanks, but it still open a lot of separate windows if we interact often.

## Proposed solution
I would love Simplified Federation to work in a single window only for every interaction. This would be closer to our experience with Twitter. 

## Alternatives
I don't have alternative at the moment, I am sorry.

## Additional context
I see that Mastodon itself _actually_ allows us to fully interact with foreign user as long as we open the username via Notification interface on our profile page. I believe @rugk knows this best. I attached two screenshots of it: 
![Mastodon can follow/unfollow foreign user in single window](https://user-images.githubusercontent.com/3586695/66798539-88923100-ef38-11e9-8d24-32e7d1f342c8.png)
(Follow/unfollow button are active, unlike if we open it outside of our own Profile page)

![Screenshot_20191015_104757](https://user-images.githubusercontent.com/3586695/66798771-44536080-ef39-11e9-9da0-8c6ebd4188f0.png)
(Reply, boost, like buttons are active, unlike if we open it outside of our own Profile page)

Thank you and please forgive my mistakes at reporting issue.

**Comment by rugk** [comment]
Yeah this is a good idea.

**Comment by rugk** [comment]
Hi @Malsasa, I've finished implementing this. See https://github.com/rugk/mastodon-simplified-federation/pull/46 (reviews would of course be appreciated).

Actually, it would be great [if you could try out the development version](https://github.com/TinyWebEx/common/blob/master/CONTRIBUTING.md#coding) and report back whether you like it or what may still be adjusted, so I can do this before the next release. In case there is something to be done… :smile:

**Comment by rugk** [comment]
BTW I am sorry for the long delay, but [this got finally released in v1.3 of this extension](https://github.com/rugk/mastodon-simplified-federation/releases/tag/v1.3).
