### ISSUE TITLE
Suppport Misskey

### ISSUE THREAD

**Issue by rugk** [rugk/mastodon-simplified-federation#63]
## Background

Misskey is another big Fediverse instance, which may benefit from such a redirect.
Test instance: https://misskey.de/@steffen

## Proposed solution

Currently nothing to propose, because I could not find any existring functionality / redirect button that we could hook into.
Except if we'd just hook any functionality.

## Alternatives

N/A

## Additional context

see https://github.com/misskey-dev/misskey/issues/2217, AFAIK this is the feature request for Misskey to have such an interface in the first place…

**Comment by austinhuang0131** [comment]
The buttons are there, so could inject like Mastodon v4

**Comment by coldReactive** [comment]
misskey.io still doesn't work btw. Still prompts to login if not logged in on misskey.

**Comment by austinhuang0131** [comment]
@coldReactive if you press the boost button then it should open a new tab (I *just* tested it). Unfortunately I haven't figured out how to remove the login prompt

**Comment by coldReactive** [comment]
> @coldReactive if you press the boost button then it should open a new tab (I _just_ tested it). Unfortunately I haven't figured out how to remove the login prompt

I just tried it by pressing + on this post on misskey, and it does nothing, it brings up the login prompt, no new tab, nothing: https://misskey.io/notes/9uiofo4g0lhs00jr

**Comment by austinhuang0131** [comment]
In extension settings did you tick the "same tab" setting

**Comment by coldReactive** [comment]
> In extension settings did you tick the "same tab" setting

I did, then I turned it off, and refreshed, still happens.

**Comment by coldReactive** [comment]
Should be noted the extension is dim/greyed out on all mastodon instances in the extension list when clicking the puzzle piece on firefox.
![image](https://github.com/rugk/mastodon-simplified-federation/assets/1313673/23446836-5e98-4ea8-bff0-de201cc51813)

**Comment by coldReactive** [comment]
Seems restarting firefox was required after installing the extension. It didn't say I needed to restart when I installed it.

**Comment by austinhuang0131** [comment]
it shouldn't require restart but it does seem that if you change the new tab thing it requires disabling then enabling the extension

if boost doesn't work but add works then likely misskey changed something, i can try to look into this again but it'll take a while

**Comment by rugk** [comment]
FYI Misskey apparently implemented https://github.com/misskey-dev/misskey/issues/2217 aka an official remote follow dialog.
See https://github.com/misskey-dev/misskey/pull/13089
