### ISSUE TITLE
https://github.com/TinyWebEx/CommonCss does not exist

### ISSUE THREAD

**Issue by Marty-Crabneck** [rugk/mastodon-simplified-federation#70]
## Bug description

`.gitmodules` references a nonexistant ressource

## Steps to reproduce

1. git clone https://github.com/rugk/mastodon-simplified-federation.gi
2. cd mastodon-simplified-federation
3. git submodule init ; git submodule update

### Actual behavior

Failed to clone 'src/common/modules/CommonCss' a second time, aborting

### Expected behavior

Ok.

## System

Operating system and version: devuan "chimaera"
Browser and version: Firefox 
Add-on version:

**Comment by rugk** [comment]
Oh sorry, thanks a lot for that report. The repo was set to private (accidentally, I guess, I don't really recall…). Now set to public, especially as I already use it… :upside_down_face:
