### ISSUE TITLE
Support Mobile Firefox [Android] [iOS]

### ISSUE THREAD

**Issue by mochsner** [rugk/mastodon-simplified-federation#78]
## Background

Creating this request to track what it would take to gain supoort of the firefox for mobile ecosystem, including Firefox on play store, f-droid open source Iceraven, Apple App store firefox, etc. 

## Proposed solution

There are currently mobile addons that exist. Need research to find what's required and if porting is feasible without major sweeping changes.

**Comment by rugk** [comment]
AFAIK its already marked as compatible on AMO and thus could be installed.

Fennec itself still hardcodes add-ons which can be installed on mobile though, so maybe it is 

It should be able to be installed on Firefox Nightly e.g.:
https://support.mozilla.org/en-US/kb/find-and-install-add-ons-firefox-android#w_expanded-extension-support-in-firefox-for-android-nightly

**Comment by rugk** [comment]
For iOS however due to technical reasons (apps on iOS need to use the safari rendering engine) addons cannot be used: https://support.mozilla.org/kb/add-ons-firefox-ios

**Comment by stop5** [comment]
I installed fennec from fdroid, added my own collection with the addon, but the browser everytime i want to put in my account at the moment i click the input field

**Comment by rugk** [comment]
Given iOS support is not possible and Android support not really productive in any way currently (i.e. Nightly as said), I'll put this on hold/blocked, as I don't think it is yer worth to put work into that.

If someone wants to submit PRs improving support or fixing things, feel free to do that though. Conceptually, it should support mobile devices, too.

**Comment by mochsner** [comment]
> AFAIK its already marked as compatible on AMO for Firefox for Android and thus could be installed.
> 
> Fennec itself still hardcodes add-ons which can be installed on mobile though, so maybe it is
> 
> It should be able to be installed on Firefox Nightly e.g.: https://support.mozilla.org/en-US/kb/find-and-install-add-ons-firefox-android#w_expanded-extension-support-in-firefox-for-android-nightly

Well, that's a bummer that Firefox doesn't support out of the box. I'm not able to see the 'expanded' list on Nightly, but I was able to see an expanded list of 'supported' applications on [Iceraven](https://github.com/fork-maintainers/iceraven-browser). Doesn't look like this plug-in is one of those "qualified" ones that show on IceRaven, though (there look to be hundreds)

**Comment by rugk** [comment]
> Doesn't look like this plug-in is one of those "supported" ones that show on IceRaven, though (there look to be hundreds, but I'm not sure what the qualifier for it is)

Likely just ask them to be added, could be they have no hard criteria.
