### ISSUE TITLE
Content Security Policy in Firefox prevents this from working

### ISSUE THREAD

**Issue by jurgenhaas** [rugk/mastodon-simplified-federation#81]
## Bug description

Just installed this plugin and configured my Mastodon address. But nothing seems to be happening. No icon in the toolbar (maybe normal) but also no functionality when trying to follow someone on a different instance.

### Actual behavior

When I open an account on any mastodon instance and look into the browser console, I can see 2 error messages which certainly explain why I don't see any functionality:

```
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). moz-extension:42:9
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("style-src"). 4 [@elhotzo](https://mastodon.social/@elhotzo)
```

## System

Operating system and version: Ubuntu 20.04 
Browser and version: Firefox 107
Add-on version: 1.4

## Possible solution

Looked at my privacy plugins uBlock Origin and the EFF Badger, but none of them has blocked anything from loading. Any other ideas?

**Comment by hueyy** [comment]
This could potentially be liked to #77. If the instances you are testing this on are on Mastodon v4, the extension will not work, which would explain why nothing seems to happen.

**Comment by rugk** [comment]
I agree to @hueyy and think the CSP error is unrelated/accidental.
To confirm, could you please provide the version number of the Mastodon instance, you are testing this on? Or just a link… the version number is shown in the footer…

**Comment by jurgenhaas** [comment]
I've just tried with https://chaos.social/@ordnung - they are using v3.5.5 and the error in the browser console is just 1 content security policy message, and the functionality is available as expected.

On https://mastodon.social/@jensclasen, where they use v4.0.2, it doesn't work.

So, your theory seems spot on.

Are you planning to support v4 eventually?

**Comment by rugk** [comment]
Duplicate of #77

**Comment by rugk** [comment]
> Are you planning to support v4 eventually?

We are it at, see/follow #77 for more information.
