### ISSUE TITLE
When using more the one account all interactions are redirected to main account (ignore logged-in instances instead)

### ISSUE THREAD

**Issue by trutzig89182** [rugk/mastodon-simplified-federation#92]
## Bug description
I have one account registered with the add on but also use another account on another server. When the add-on is activated, tryting to reply to a post, to boost it or favour leads to an error. When I de-activate the plugin, all works fine. Somebody else noted similar problems and these were resolved when she deactivated the plugin. 

## Steps to reproduce

1. install the plugin, an register a mastodon account
2. open another account on another browser in Firefox
3. for any post click on reply, boot, or favour

### Actual behavior
leads to error

### Expected behavior
do what the buttons are supposed to to

## System

Operating system and version: 
Browser and version: 107.0.1 
Add-on version: 2.0

**Comment by trutzig89182** [comment]
While I wrote this the behaviour seems to have changed. Now, instead of giving back an error, the post is opened with my main account registered with the plugin. This is close to what the plugin is supposed to do, of course, still it makes it unusable for me, as I have to deal with accounts for other institution at the same time.

**Comment by Book1312** [comment]
Getting the same issue, clicking on any interact button on the site of  -reply, boost, fav, bookmark and ...- from an instance I'm registred on but that isn't the one registred in the extension settings opens the toot in the "primary" instance.
This wasn't the behaviour I was getting a few days ago.

**Comment by rugk** [comment]
Yeah this is an rather unfortunate issue of the fact that the addon works "too good" and obviously redirects all instances.
Only https://github.com/rugk/mastodon-simplified-federation/issues/28 i.e. multi-instance support could properly solve that, but a quick fix could be to just ignore logged-in instances/instances wäre youre logged-in hmm.

**Comment by trutzig89182** [comment]
Perhaps a quick fix could be an option to allow an ingore list to be added to the plugin? This way it would not need to automatically detect if you are logged it, but would simply filter out some domains.

**Comment by rugk** [comment]
I guess that would be as hard as implementing automatic detection.

**Comment by Anglodel** [comment]
Same issue here.
Glad to hear it's already under consideration !
Bon courage, for developing this add-on o/
