### ISSUE TITLE
Do not inject mastodon-simplified-federation-injected class on each website

### ISSUE THREAD

**Issue by rugk** [rugk/mastodon-simplified-federation#95]
## Bug description

A [user on AMO](https://addons.mozilla.org/de/android/addon/mastodon-simplified-federation/reviews/1921279/) correctly noticed the extension always injects a class called `mastodon-simplified-federation-injected` onto the body of each website – _even non-Mastodon websites_.

## Steps to reproduce

1. Install extension.
2. Go to any website.
3. Look in the developer tools for `.mastodon-simplified-federation-injected`.

### Actual behavior

`mastodon-simplified-federation-injected` is injected on `body`.

### Expected behavior

This injection should _at most_ only happen on Mastodon instances, or not at all.
It can disturb users (actually the user in question noticed this as a red flag about the extension, which arguably, it can be).

## System

Browser and version: Firefox 108
Add-on version: 2.0

## Possible solution

The code that causes this is here:
https://github.com/rugk/mastodon-simplified-federation/blob/5e014f3a52747e2b3424027a410358d6f7d602c1/src/content_script/mastodonInject.js#L150-L157

As you can see, it is a simple guard to prevent the extension from running twice. It has been introduced in #84.

Maybe a solution could be to use a variable instead that is defined and _if already defined_ not re-defined? To prevent a double-injection?

/cc @hueyy

**Comment by hueyy** [comment]
Agreed, that definitely isn't ideal. #97 should fix this.
