### ISSUE TITLE
Attempting to act on boosts on profile feeds result in Mastodon error

### ISSUE THREAD

**Issue by austinhuang0131** [rugk/mastodon-simplified-federation#96]
## Bug description
Attempting to act on boosts on profile feeds result in Mastodon error (cannot find activity) as it's using the boost activity ID instead of the original activity ID.

## Steps to reproduce

1. Go to any profile feed on a v4 instance.
2. Act (fav/boost) on a boosted post. (Clicking the post then fav/boost does work)

### Actual behavior
The boost's activity ID is referenced in the callback, which results in an error on the home instance's side.

### Expected behavior
The original activity ID is used for callback.

## System

Operating system and version: not relevant
Browser and version: Firefox 
Add-on version: 2.0

## Possible solution
Fetch original activity ID?

**Comment by hueyy** [comment]
Yes you're right, the activity ID being used was wrong. Should be fixed by #98.
